### ISSUE TITLE
Create an adaption of the path_following_node to be used for pipeline following.

### ISSUE THREAD

**Issue by Tuuvaab** [vortexntnu/deprecated-vortex-cv#113]

**Comment by Lasgut** [comment]
Trying to run some test code that uses different functions from the cv repo with docker, but i am not able to plot the image in order to visualize the image processing. This would make the testing more intuitive. Should be able to perform some plots during the beginning of next sunday. If not another approach should be considered.

**Comment by Lasgut** [comment]
Finally!! im able to use pyplot in docker. Solution: in docker compose enviorment: - DISPLAY=$DISPLAY  and  install tk
